formatter: markdown
settings:
  anchor: true
  color: true
  default: true
  escape: true
  html: true
  indent: 4
  required: true
  sensitive: true
  type: true

sort:
  enabled: true
  by: required

output:
  file: README.md
  mode: replace
  template: |-
    {{ .Content }}
    {{- printf "\n" -}}
